import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[shell]
program = "/opt/homebrew/opt/fish/bin/fish"


[font]
size = 13.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.5
blur = true
option_as_alt = "Both"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^\u27e8\u27e9`]+"
command = "open" # On macOS
# command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = true 
mouse.enabled = true
binding = { key = "O", mods = "Control" }

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
chars = "\u0013j"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bOH"
mods = "Command"
key = "Left"

[[keyboard.bindings]]
chars = "\u001bOF"
mods = "Command"
key = "Right"

[[keyboard.bindings]]
chars = "\u0015"
mods = "Command"
key = "Back"

[[keyboard.bindings]]
chars = "\u001b\u007f"
mods = "Alt"
key = "Back"

